name: restaurantour
description: Flutter developer coding challenge starter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  bloc_test: ^9.0.2
  mockito: ^5.0.15
  mocktail: ^0.2.0


flutter:
  uses-material-design: true
#  assets:
#    - assets/svg/